# Generated by Django 4.0.4 on 2022-05-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_created_on_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.RemoveField(
            model_name='like',
            name='commentLike',
        ),
    ]
